// GENERATED by tools/gen_settings.py from app/settings.py (UI_SETTINGS).
// Do not edit: change settings.py and run `python tools/gen_settings.py`;
// app/tests/test_settings_schema.py fails while this file is stale.
//
// What the Settings panel exposes, as data. The command palette needs to
// offer settings by name, and App.jsx cannot read them out of Settings.jsx:
// that panel is a lazy chunk, and its controls are JSX rather than a list.
// `section` matches the panel's section title, so a palette hit can say
// where it is going. `label` matches the control's label -- that is what
// the panel's own search box matches on, and jumping works by handing it
// that string. test_ui_settings_catalog.py keeps this and Settings.jsx in
// step: every key here must be bound by the panel, and vice versa.
export const SETTINGS_CATALOG = [
  // Server
  { key: 'server_share', label: 'Public server (share)', section: 'Server' },
  { key: 'clear_output', label: 'Clear output folder before each run', section: 'Server' },
  { key: 'server_name', label: 'Server name', section: 'Server' },
  { key: 'server_port', label: 'Server port', section: 'Server' },
  { key: 'output_template', label: 'Filename output template', section: 'Server' },
  { key: 'faceset_library_path', label: 'Faceset library folder', section: 'Server' },

  // Performance
  { key: 'provider', label: 'Provider', section: 'Performance' },
  { key: 'trt_precision', label: 'Precision mode (TensorRT)', section: 'Performance' },
  { key: 'swap_quantization', label: 'Swap model quantization (INT8/FP8)', section: 'Performance' },
  { key: 'force_cpu', label: 'Force CPU for face analyser', section: 'Performance' },
  { key: 'auto_thread_selection', label: 'Auto thread selection', section: 'Performance' },
  { key: 'face_detector_threshold', label: 'Face detection threshold', section: 'Performance' },
  { key: 'face_detector_nms', label: 'Overlap NMS threshold', section: 'Performance' },
  { key: 'detector_scale_pyramid', label: 'Detector scale pyramid', section: 'Performance' },
  { key: 'max_threads', label: 'Max threads', section: 'Performance' },
  { key: 'memory_limit', label: 'Max memory (GB)', section: 'Performance' },

  // Advanced performance
  { key: 'perf_trt_pool', label: 'Swapper TRT pool', section: 'Advanced performance' },
  { key: 'trt_builder_optimization_level', label: 'TensorRT builder optimization', section: 'Advanced performance' },
  { key: 'trt_auxiliary_streams', label: 'TensorRT auxiliary streams', section: 'Advanced performance' },
  { key: 'trt_cuda_graph', label: 'TensorRT CUDA graphs (experimental)', section: 'Advanced performance' },
  { key: 'cpu_opencv_threads', label: 'CPU OpenCV kernel threads', section: 'Advanced performance' },
  { key: 'perf_detmask_pool', label: 'Detect/Mask pool', section: 'Advanced performance' },
  { key: 'perf_detector_pool', label: 'Detector pool', section: 'Advanced performance' },
  { key: 'perf_expr_pool', label: 'Expression pool', section: 'Advanced performance' },
  { key: 'perf_encoder_preset', label: 'Encoder preset', section: 'Advanced performance' },
  { key: 'perf_nvdec', label: 'GPU video decode (NVDEC)', section: 'Advanced performance' },
  { key: 'perf_batch_swap', label: 'Batched swap', section: 'Advanced performance' },
  { key: 'perf_profile', label: 'Stage profiling (terminal)', section: 'Advanced performance' },
  { key: 'cpu_ort_intra_threads', label: 'ONNX intra-op threads', section: 'Advanced performance' },
  { key: 'cpu_ort_inter_threads', label: 'ONNX inter-op threads', section: 'Advanced performance' },
  { key: 'cpu_ffmpeg_threads', label: 'FFmpeg encoder threads', section: 'Advanced performance' },
  { key: 'perf_ort_arena_strategy', label: 'ONNX memory arena', section: 'Advanced performance' },
  { key: 'perf_cudnn_conv_algo', label: 'cuDNN conv algorithm search', section: 'Advanced performance' },
  { key: 'perf_gpu_mem_limit', label: 'Provider memory limit (MiB)', section: 'Advanced performance' },
  { key: 'vram_safety_margin_gb', label: 'VRAM safety margin (GB)', section: 'Advanced performance' },
  { key: 'perf_batch_max', label: 'Cross-frame swap batch', section: 'Advanced performance' },
  { key: 'perf_nvenc_preset', label: 'NVENC preset', section: 'Advanced performance' },
  { key: 'perf_gpu_affine', label: 'CUDA affine warp', section: 'Advanced performance' },
  { key: 'perf_pinned_buffers', label: 'Pinned host buffers (zero-copy)', section: 'Advanced performance' },
  { key: 'temporal_step', label: 'Face tracking interval (frames)', section: 'Advanced performance' },

  // Identity & tracking
  { key: 'recognizer', label: 'Recognition model', section: 'Identity & tracking' },
  { key: 'identity_confidence_threshold', label: 'Identity confidence threshold', section: 'Identity & tracking' },
  { key: 'face_demarcate', label: 'Interacting-face demarcation', section: 'Identity & tracking' },
  { key: 'track_stitch', label: 'Track stitching', section: 'Identity & tracking' },
  { key: 'verify_swap', label: 'Swap outcome guard', section: 'Identity & tracking' },
  { key: 'upright_remeasure', label: 'Upright re-measure (rolled faces)', section: 'Identity & tracking' },
  { key: 'process_priority', label: 'Process priority', section: 'Identity & tracking' },

  // Output
  { key: 'output_image_format', label: 'Image format', section: 'Output' },
  { key: 'output_video_format', label: 'Video format', section: 'Output' },
  { key: 'output_video_codec', label: 'Video codec', section: 'Output' },
  { key: 'video_quality', label: 'Video quality', section: 'Output' },
  { key: 'use_os_temp_folder', label: 'Use OS temp folder', section: 'Output' },
  { key: 'output_show_video', label: 'Show video in browser (re-encodes)', section: 'Output' },
  { key: 'synthetic_label', label: 'Label output as synthetic media (metadata tag)', section: 'Output' },
  { key: 'synthetic_watermark', label: 'Visible watermark on output', section: 'Output' },
  { key: 'synthetic_watermark_text', label: 'Watermark text', section: 'Output' },
];

// The event the palette fires to send the Settings panel to one control. The
// panel is a lazy chunk that may not be mounted yet when the command runs, so
// this is a window event with a retry on the panel's side rather than a direct
// call -- the same bus pattern the Face Swap actions already use.
export const FOCUS_SETTING_EVENT = 'roop:focus-setting';

export const focusSetting = (key) => {
  window.dispatchEvent(new CustomEvent(FOCUS_SETTING_EVENT, { detail: { key } }));
};
