"""Evidence-based storage inventory and guarded cleanup.

This module deliberately owns a small, explicit set of application roots.  It
does not scan a user's drive and it never treats a filename by itself as proof
that an item is disposable.  Every item is classified from its root ownership,
the current application references, and the regeneration contract recorded in
``CATEGORY_DEFINITIONS``.
"""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import threading
from pathlib import Path
from typing import Any, Iterable, Mapping


SAFE_TO_DELETE = "SAFE_TO_DELETE"
REVIEW_BEFORE_DELETE = "REVIEW_BEFORE_DELETE"
PROTECTED = "PROTECTED"
UNKNOWN = "UNKNOWN"

_ACTIVE_STATES = {
    "PREPARING", "PROCESSING", "PAUSE_REQUESTED", "PAUSED",
    "INTERRUPTED", "RECOVERABLE",
}

CATEGORY_DEFINITIONS = {
    "application cache": {
        "status": "VERIFIED",
        "evidence": "app/models/trt_cache, app/models/runtime_profiles, .pytest_cache, .ruff_cache, and React dist are generated by the application/toolchain; TensorRT/profile caches are kept review-only.",
    },
    "preview cache": {
        "status": "VERIFIED_NO_DISK_ROOT",
        "evidence": "app/roop/live_preview.py stores the current preview in process memory; no application-owned on-disk preview cache was found.",
    },
    "temporary files": {
        "status": "VERIFIED",
        "evidence": "app/ui/main.py and app/api.py use app/temp; app/api_media.py writes upload files under app/temp/api_uploads.",
    },
    "logs": {
        "status": "VERIFIED",
        "evidence": "The repository AGENTS.md documents root logs/{api,dev,shell}; this checkout contains root logs/api, logs/dev, and logs/sessions.",
    },
    "model downloads": {
        "status": "VERIFIED",
        "evidence": "Model loaders and app/README.md use app/models; Pinokio documents cache/HF_HOME and cache/TORCH_HOME as model caches.",
    },
    "installers": {
        "status": "UNKNOWN",
        "evidence": "No application-owned installer artifact directory is declared by the repository. install.js and torch.js are scripts, not deletable downloaded artifacts.",
    },
    "package caches": {
        "status": "UNKNOWN",
        "evidence": "The repository does not declare a package-manager cache root. Unscoped user uv/pip/npm caches are intentionally not inventoried.",
    },
    "old environments": {
        "status": "VERIFIED",
        "evidence": "app/env is the active Pinokio environment and is protected; no second application environment root is declared.",
    },
    "required dependencies": {
        "status": "VERIFIED",
        "evidence": "start_react.js serves the current React tree and its installed node_modules; these dependencies are not cleanup candidates.",
    },
    "orphaned files": {
        "status": "VERIFIED_WITH_LIMITATION",
        "evidence": "Only files under known application roots with no current project, queue, loaded-media, or active-work reference can be identified; no drive-wide orphan scan is performed.",
    },
    "incomplete downloads": {
        "status": "VERIFIED",
        "evidence": "app/roop/utilities.py downloads to <model>.part and atomically renames on success; a leftover .part file is review-only because active ownership cannot be proven from its name.",
    },
    "unsupported files": {
        "status": "UNKNOWN",
        "evidence": "No application manifest defines arbitrary unsupported files; such files are not promoted to safe deletion.",
    },
    "Pinokio-generated disposable files": {
        "status": "VERIFIED_WITH_LIMITATION",
        "evidence": "PINOKIO.md documents cache/HF_HOME, TORCH_HOME, and GRADIO_TEMP_DIR; the checkout also contains .pinokio-temp. These paths are review-only because ownership and active use are not fully exposed to the application.",
    },
}


class StorageError(RuntimeError):
    """A user-actionable storage operation failure."""

    def __init__(self, message: str, status_code: int = 409):
        super().__init__(message)
        self.status_code = status_code


def _canonical(path: str | os.PathLike[str]) -> str:
    return os.path.normcase(os.path.realpath(os.path.abspath(os.fspath(path))))


def _within(path: str, root: str) -> bool:
    try:
        return os.path.commonpath([_canonical(path), _canonical(root)]) == _canonical(root)
    except ValueError:
        return False


def _size(path: str) -> int:
    try:
        if os.path.isfile(path) and not os.path.islink(path):
            return int(os.path.getsize(path))
        if not os.path.isdir(path) or os.path.islink(path):
            return 0
    except OSError:
        return 0
    total = 0
    for dirpath, dirnames, filenames in os.walk(path, followlinks=False):
        dirnames[:] = [d for d in dirnames
                       if not os.path.islink(os.path.join(dirpath, d))]
        for filename in filenames:
            candidate = os.path.join(dirpath, filename)
            try:
                if not os.path.islink(candidate):
                    total += int(os.path.getsize(candidate))
            except OSError:
                continue
    return total


def _item_id(path: str) -> str:
    return hashlib.sha256(_canonical(path).encode("utf-8")).hexdigest()[:24]


def _path_strings(value: Any, keys: tuple[str, ...] = ()) -> Iterable[str]:
    """Yield path values from known checkpoint/queue fields only."""
    if isinstance(value, Mapping):
        for key, child in value.items():
            key_name = str(key).lower()
            if key_name in {
                "path", "filename", "source_path", "target_path",
                "manifest", "directory", "output_path",
            }:
                if isinstance(child, str) and child:
                    yield child
            yield from _path_strings(child, keys + (key_name,))
    elif isinstance(value, (list, tuple)):
        for child in value:
            yield from _path_strings(child, keys)


class StorageManager:
    """Inventory known runtime roots and delete only a revalidated safe item."""

    def __init__(self, project_root: str | None = None):
        self.project_root = os.path.abspath(project_root or
                                            os.path.dirname(os.path.dirname(__file__)))
        self.app_root = os.path.join(self.project_root, "app")
        self._lock = threading.RLock()

    def _runtime(self) -> dict[str, Any]:
        context: dict[str, Any] = {
            "references": set(),
            "active_work": False,
            "active_reasons": [],
        }
        try:
            import api
            progress = getattr(api, "_progress", {}) or {}
            if bool(progress.get("processing")):
                context["active_work"] = True
                context["active_reasons"].append("live processing is active")
            for entry in getattr(api, "list_files_process", []) or []:
                filename = getattr(entry, "filename", "")
                if filename:
                    context["references"].add(_canonical(filename))
            active_project = getattr(api, "_active_project_id", "")
            if active_project:
                context["references"].add(_canonical(
                    os.path.join(self.app_root, "projects", f"{active_project}.json")))
        except Exception:
            # Inventory must remain available when the API is starting or when
            # the unit-test process intentionally has no backend imported.
            pass

        try:
            import routes_queue
            queue = getattr(routes_queue, "_queue", {}) or {}
            if queue.get("current") or queue.get("running"):
                context["active_work"] = True
                context["active_reasons"].append("queue processing is active")
            for job in queue.get("jobs", []) or []:
                state = str(job.get("state") or "")
                if state in _ACTIVE_STATES:
                    context["active_work"] = True
                    context["active_reasons"].append("a resumable queue/project job exists")
                context["references"].update(
                    _canonical(p) for p in _path_strings(job) if p)
        except Exception:
            pass

        queue_file = os.path.join(self.app_root, "queue.json")
        if os.path.isfile(queue_file):
            context["references"].add(_canonical(queue_file))
            try:
                with open(queue_file, encoding="utf-8") as handle:
                    data = json.load(handle)
                for job in data.get("jobs", []) or []:
                    state = str(job.get("state") or "")
                    if state in _ACTIVE_STATES:
                        context["active_work"] = True
                        context["active_reasons"].append("a persisted active/resumable queue job exists")
                    context["references"].update(
                        _canonical(p) for p in _path_strings(job) if p)
            except (OSError, ValueError, json.JSONDecodeError):
                # A malformed queue is protected; it is not safe to infer that
                # its referenced media is orphaned.
                context["active_work"] = True
                context["active_reasons"].append("queue references could not be read")

        projects_dir = os.path.join(self.app_root, "projects")
        if os.path.isdir(projects_dir):
            for filename in os.listdir(projects_dir):
                if not filename.endswith(".json"):
                    continue
                path = os.path.join(projects_dir, filename)
                context["references"].add(_canonical(path))
                try:
                    with open(path, encoding="utf-8") as handle:
                        record = json.load(handle)
                    context["references"].update(
                        _canonical(p) for p in _path_strings(record) if p)
                    if str(record.get("state") or "") in _ACTIVE_STATES:
                        context["active_work"] = True
                        context["active_reasons"].append("a persisted project is active or resumable")
                except (OSError, ValueError, json.JSONDecodeError):
                    context["active_work"] = True
                    context["active_reasons"].append("a project checkpoint could not be read")

        context["active_reasons"] = list(dict.fromkeys(context["active_reasons"]))
        return context

    def _root(self, relative: str) -> str:
        return os.path.join(self.project_root, relative.replace("/", os.sep))

    def _known_safe_path(self, path: str) -> bool:
        safe_roots = [
            os.path.join(self.project_root, ".pytest_cache"),
            os.path.join(self.app_root, ".pytest_cache"),
            os.path.join(self.project_root, ".ruff_cache"),
            os.path.join(self.app_root, ".ruff_cache"),
            os.path.join(self.project_root, "react-ui", "dist"),
        ]
        for root in safe_roots:
            if _canonical(path) == _canonical(root):
                return True
        # Python bytecode directories are discovered by their actual location,
        # not by deleting arbitrary files with a .pyc suffix.
        if os.path.basename(path) == "__pycache__" and _within(path, self.app_root):
            return True
        return False

    def _referenced(self, path: str, references: set[str]) -> bool:
        return any(_within(path, ref) or _within(ref, path) for ref in references)

    def _make_item(self, path: str, category: str, classification: str,
                   reason: str, regenerable: bool, context: Mapping[str, Any],
                   evidence: str = "") -> dict[str, Any]:
        canonical = _canonical(path)
        referenced = self._referenced(canonical, context["references"])
        active = bool(context["active_work"])
        if referenced:
            classification = PROTECTED
            reason = "Referenced by a loaded target, queue job, project checkpoint, or partial output."
        elif active and classification == SAFE_TO_DELETE:
            classification = PROTECTED
            reason = "Cleanup is blocked while processing or resumable queue/project work is active."
        return {
            "id": _item_id(canonical),
            "path": os.path.abspath(path),
            "relative_path": os.path.relpath(path, self.project_root),
            "category": category,
            "classification": classification,
            "reason": reason,
            "regenerable": bool(regenerable),
            "referenced": bool(referenced),
            "reference_count": sum(1 for ref in context["references"]
                                   if _within(canonical, ref) or _within(ref, canonical)),
            "size_bytes": _size(path),
            "is_directory": os.path.isdir(path) and not os.path.islink(path),
            "evidence": evidence,
        }

    def _children(self, relative: str) -> list[str]:
        path = self._root(relative)
        if not os.path.isdir(path) or os.path.islink(path):
            return []
        try:
            return [os.path.join(path, name) for name in os.listdir(path)]
        except OSError:
            return []

    def _pycache_dirs(self) -> list[str]:
        result = []
        for base in (self.app_root, os.path.join(self.project_root, "react-ui")):
            if not os.path.isdir(base):
                continue
            for directory, dirnames, _files in os.walk(base, followlinks=False):
                dirnames[:] = [d for d in dirnames
                               if d not in {"env", "node_modules", ".git"}
                               and not os.path.islink(os.path.join(directory, d))]
                if "__pycache__" in dirnames:
                    result.append(os.path.join(directory, "__pycache__"))
        return result

    def scan(self) -> dict[str, Any]:
        with self._lock:
            context = self._runtime()
            items: list[dict[str, Any]] = []

            def add(path: str, category: str, classification: str,
                    reason: str, regenerable: bool, evidence: str = ""):
                if os.path.lexists(path):
                    items.append(self._make_item(path, category, classification,
                                                 reason, regenerable, context, evidence))

            # Data and runtime roots are listed as protected containers so the
            # UI makes the safety boundary visible without enumerating models or
            # user media into a huge response.
            protected = [
                ("app/env", "old environments", "Active app/env is the required Pinokio environment."),
                ("app/models", "model downloads", "Model files are required inputs and active model artifacts are never cleanup candidates."),
                ("app/output", "user outputs", "Rendered output is user data and may include the only valid resume prefix."),
                ("app/facesets", "active project data", "Saved face libraries are user data."),
                ("app/projects", "checkpoints", "Project checkpoint records reconstruct resumable work."),
                ("app/queue.json", "files referenced by active jobs", "The durable queue owns pending and resumable job references."),
                ("react-ui/node_modules", "required dependencies", "The active React UI dependency tree is required by start_react.js."),
            ]
            for relative, category, reason in protected:
                add(self._root(relative), category, PROTECTED, reason, False)

            for path in self._children("app/temp/api_uploads") + self._children("app/temp/faceset"):
                add(path, "temporary files", SAFE_TO_DELETE,
                    "Application upload/faceset scratch can be recreated; the exact file is protected when referenced.",
                    True, CATEGORY_DEFINITIONS["temporary files"]["evidence"])

            # This is the actual on-disk cache root documented by Pinokio. Model
            # caches are protected; only Gradio's disposable cache is review.
            for child in self._children("cache"):
                name = os.path.basename(child)
                if name in {"HF_HOME", "TORCH_HOME"}:
                    add(child, "model downloads", PROTECTED,
                        "Pinokio documents this cache as a model download cache.", False,
                        CATEGORY_DEFINITIONS["model downloads"]["evidence"])
                elif name == "GRADIO_TEMP_DIR":
                    add(child, "preview cache", REVIEW_BEFORE_DELETE,
                        "Pinokio documents this as Gradio-generated temporary data; the application cannot prove it is not in use by another Pinokio shell.",
                        True, CATEGORY_DEFINITIONS["Pinokio-generated disposable files"]["evidence"])
                else:
                    add(child, "unsupported files", REVIEW_BEFORE_DELETE,
                        "Located under a known Pinokio cache root but not covered by a repository-supported cache contract.",
                        False, CATEGORY_DEFINITIONS["unsupported files"]["evidence"])

            for child in self._children(".pinokio-temp"):
                add(child, "Pinokio-generated disposable files", REVIEW_BEFORE_DELETE,
                    "Pinokio-generated temporary content is review-only because active ownership is outside the application API.",
                    True, CATEGORY_DEFINITIONS["Pinokio-generated disposable files"]["evidence"])

            for child in self._children("logs"):
                if os.path.isdir(child) and not os.path.islink(child):
                    for directory, _dirs, filenames in os.walk(child, followlinks=False):
                        for filename in filenames:
                            log_path = os.path.join(directory, filename)
                            if filename in {"latest", "events"}:
                                add(log_path, "logs", PROTECTED,
                                    "The troubleshooting contract points at this current log alias.", False)
                            else:
                                add(log_path, "logs", SAFE_TO_DELETE,
                                    "Historical log file; the current/latest and events aliases are protected.",
                                    True, CATEGORY_DEFINITIONS["logs"]["evidence"])

            for relative in (".pytest_cache", "app/.pytest_cache", ".ruff_cache", "app/.ruff_cache",
                             "react-ui/dist"):
                add(self._root(relative), "application cache", SAFE_TO_DELETE,
                    "Generated tool/build cache; the application recreates it on demand.", True,
                    CATEGORY_DEFINITIONS["application cache"]["evidence"])
            for path in self._pycache_dirs():
                add(path, "application cache", SAFE_TO_DELETE,
                    "Python bytecode cache under an application source tree; Python regenerates it.", True,
                    CATEGORY_DEFINITIONS["application cache"]["evidence"])

            for child in self._children("app/models/trt_cache"):
                add(child, "application cache", REVIEW_BEFORE_DELETE,
                    "TensorRT engines/timing/profile data is regenerable but hardware/provider/precision-sensitive; inspect before deletion.",
                    True, CATEGORY_DEFINITIONS["application cache"]["evidence"])
            add(self._root("app/models/runtime_profiles"), "application cache", REVIEW_BEFORE_DELETE,
                "Runtime profile data is regenerable but contains hardware/workload calibration assumptions.", True,
                CATEGORY_DEFINITIONS["application cache"]["evidence"])

            models_root = self._root("app/models")
            if os.path.isdir(models_root):
                for directory, _dirs, filenames in os.walk(models_root, followlinks=False):
                    for filename in filenames:
                        if not filename.endswith(".part"):
                            continue
                        add(os.path.join(directory, filename), "incomplete downloads",
                            REVIEW_BEFORE_DELETE,
                            "The downloader uses .part as an interrupted model-transfer marker; ownership and retry intent require review.",
                            True, CATEGORY_DEFINITIONS["incomplete downloads"]["evidence"])

            # A second root-level models directory is present in this checkout,
            # but the active launcher and model loaders resolve app/models. It is
            # therefore surfaced as unverified ownership rather than treated as
            # an application model library. Its contents are never safe-delete.
            external_models = self._root("models")
            if os.path.lexists(external_models) and _canonical(external_models) != _canonical(models_root):
                add(external_models, "unsupported files", REVIEW_BEFORE_DELETE,
                    "A root-level models directory exists, but the application contract resolves models under app/models; ownership is unverified.",
                    False, CATEGORY_DEFINITIONS["unsupported files"]["evidence"])
                if os.path.isdir(external_models):
                    for directory, _dirs, filenames in os.walk(external_models, followlinks=False):
                        for filename in filenames:
                            if filename.endswith(".part"):
                                add(os.path.join(directory, filename), "unsupported files", REVIEW_BEFORE_DELETE,
                                    "This partial-looking artifact is outside the verified app/models download root and cannot be safely identified as an application download.",
                                    False, CATEGORY_DEFINITIONS["unsupported files"]["evidence"])

            # The root temp directory exists in this checkout, but the active
            # launcher runs the application from app/ and source does not declare
            # this sibling as an application root. Show it as review-only rather
            # than guessing that it is disposable.
            for child in self._children("temp"):
                add(child, "unsupported files", REVIEW_BEFORE_DELETE,
                    "Observed outside the application-owned app/temp root; ownership is unverified.", False,
                    CATEGORY_DEFINITIONS["unsupported files"]["evidence"])

            items.sort(key=lambda item: (item["classification"], item["category"], item["path"].lower()))
            categories = []
            for name, definition in CATEGORY_DEFINITIONS.items():
                category_items = [item for item in items if item["category"] == name]
                categories.append({
                    "name": name,
                    **definition,
                    "item_count": len(category_items),
                    "size_bytes": sum(item["size_bytes"] for item in category_items),
                })
            return {
                "schema_version": 1,
                "project_root": self.project_root,
                "active_work": bool(context["active_work"]),
                "active_reasons": context["active_reasons"],
                "categories": categories,
                "items": items,
                "deletion_policy": "Only a single freshly revalidated SAFE_TO_DELETE item may be explicitly deleted.",
            }

    def delete_item(self, item_id: str, confirm: bool = False) -> dict[str, Any]:
        if not confirm:
            raise StorageError("explicit confirmation is required before deleting storage")
        with self._lock:
            inventory = self.scan()
            item = next((entry for entry in inventory["items"]
                         if entry["id"] == str(item_id)), None)
            if item is None:
                raise StorageError("storage item is no longer present; refresh the review")
            if item["classification"] != SAFE_TO_DELETE:
                raise StorageError(
                    f"item is {item['classification']} and cannot be deleted by the storage manager")
            path = item["path"]
            if not self._known_safe_path(path) and item["category"] != "logs" and item["category"] != "temporary files":
                raise StorageError("storage item is outside the verified safe deletion roots")
            if os.path.islink(path) or not any(_within(path, self._root(root))
                                              for root in (
                                                  ".pytest_cache", "app/.pytest_cache", ".ruff_cache",
                                                  "app/.ruff_cache", "react-ui/dist",
                                                  "app", "logs")):
                raise StorageError("refusing to delete a symlink or unowned path")
            try:
                if os.path.isdir(path):
                    shutil.rmtree(path)
                else:
                    os.remove(path)
            except OSError as exc:
                raise StorageError(f"could not delete {item['relative_path']}: {exc}") from exc
            return {"deleted": item, "inventory": self.scan()}


__all__ = [
    "CATEGORY_DEFINITIONS", "PROTECTED", "REVIEW_BEFORE_DELETE", "SAFE_TO_DELETE",
    "StorageError", "StorageManager", "UNKNOWN",
]
