"""Render the generated settings files from app/settings.py.

    python tools/gen_settings.py            # (re)write both files
    python tools/gen_settings.py --check    # exit 1 if either committed file is stale

Outputs, both committed:
  app/settings.schema.json                     every setting: default, UI entry, env mapping
  react-ui/src/components/settingsCatalog.js   SETTINGS_CATALOG for the command palette

The source is app/settings.py: names and defaults from Settings._load(),
labels/sections from UI_SETTINGS, ROOP_* mapping from ENV_SETTINGS. Defaults
are read from a Settings instance pointed at a file that does not exist -- the
same throwaway /api/settings/defaults builds -- so nothing on the generating
machine's config leaks in. A few values are facts about the machine rather than
defaults (the GPU probe, the CPU count, the admitted execution provider) and
are recorded as `derived` without a value.
app/tests/test_settings_schema.py runs this in --check mode.
"""
from __future__ import annotations

import argparse
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP = os.path.join(ROOT, "app")
if APP not in sys.path:
    sys.path.insert(0, APP)

SCHEMA_PATH = os.path.join(APP, "settings.schema.json")
CATALOG_PATH = os.path.join(ROOT, "react-ui", "src", "components", "settingsCatalog.js")
# Machine facts, not defaults: the GPU probe, the CPU count, and the execution
# provider Settings admits from what onnxruntime exposes on this machine.
DERIVED = {"hardware", "hardware_signature", "max_threads",
           "provider", "provider_requested", "provider_admitted", "provider_active"}
SCHEMA_VERSION = 1


def _defaults():
    import settings
    inst = settings.Settings(os.path.join(APP, "__settings_schema_probe_does_not_exist__.yaml"))
    return {k: v for k, v in vars(inst).items() if not k.startswith("_") and k != "config_file"}


def build_schema():
    import settings
    defaults = _defaults()
    ui = {k: (label, section) for k, label, section in settings.UI_SETTINGS}
    env = {k: (var, kind) for k, var, kind in settings.ENV_SETTINGS}
    unknown_ui = [k for k in ui if k not in defaults]
    if unknown_ui:
        raise SystemExit(f"UI_SETTINGS names settings that Settings._load() does not define: {unknown_ui}")
    # An env mapping may name a key that only exists in config.yaml by hand
    # (no Settings attribute, no UI): run.py has always read the raw YAML for
    # these. They are kept, and the schema says so.
    config_only = [k for k in env if k not in defaults]
    out = {}
    for key, value in defaults.items():
        entry = {}
        if key in DERIVED:
            entry["derived"] = True
        else:
            entry["default"] = value
        entry["type"] = type(value).__name__ if value is not None else "null"
        if key in ui:
            entry["ui"] = {"label": ui[key][0], "section": ui[key][1]}
        if key in env:
            entry["env"] = {"var": env[key][0], "kind": env[key][1]}
        out[key] = entry
    for key in config_only:
        out[key] = {"config_only": True, "type": "unknown",
                    "env": {"var": env[key][0], "kind": env[key][1]}}
    return {
        "$comment": "GENERATED by tools/gen_settings.py from app/settings.py -- do not edit; "
                    "edit settings.py and re-run the generator.",
        "schema_version": SCHEMA_VERSION,
        "ui_order": [k for k, _, _ in settings.UI_SETTINGS],
        "settings": out,
    }


def render_schema(schema):
    return json.dumps(schema, indent=2, ensure_ascii=False) + "\n"


def _js(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def render_catalog():
    import settings
    lines = [
        "// GENERATED by tools/gen_settings.py from app/settings.py (UI_SETTINGS).",
        "// Do not edit: change settings.py and run `python tools/gen_settings.py`;",
        "// app/tests/test_settings_schema.py fails while this file is stale.",
        "//",
        "// What the Settings panel exposes, as data. The command palette needs to",
        "// offer settings by name, and App.jsx cannot read them out of Settings.jsx:",
        "// that panel is a lazy chunk, and its controls are JSX rather than a list.",
        "// `section` matches the panel's section title, so a palette hit can say",
        "// where it is going. `label` matches the control's label -- that is what",
        "// the panel's own search box matches on, and jumping works by handing it",
        "// that string. test_ui_settings_catalog.py keeps this and Settings.jsx in",
        "// step: every key here must be bound by the panel, and vice versa.",
        "export const SETTINGS_CATALOG = [",
    ]
    last = None
    for key, label, section in settings.UI_SETTINGS:
        if section != last:
            if last is not None:
                lines.append("")
            lines.append(f"  // {section}")
            last = section
        lines.append(f"  {{ key: {_js(key)}, label: {_js(label)}, section: {_js(section)} }},")
    lines += [
        "];",
        "",
        "// The event the palette fires to send the Settings panel to one control. The",
        "// panel is a lazy chunk that may not be mounted yet when the command runs, so",
        "// this is a window event with a retry on the panel's side rather than a direct",
        "// call -- the same bus pattern the Face Swap actions already use.",
        "export const FOCUS_SETTING_EVENT = 'roop:focus-setting';",
        "",
        "export const focusSetting = (key) => {",
        "  window.dispatchEvent(new CustomEvent(FOCUS_SETTING_EVENT, { detail: { key } }));",
        "};",
        "",
    ]
    return "\n".join(lines)


def outputs():
    return {SCHEMA_PATH: render_schema(build_schema()), CATALOG_PATH: render_catalog()}


def _read(path):
    try:
        with open(path, encoding="utf-8", newline="") as fh:
            return fh.read()
    except FileNotFoundError:
        return None


def stale():
    """The generated files whose committed content differs from the render."""
    return [p for p, text in outputs().items() if (_read(p) or "").replace("\r\n", "\n") != text]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="report stale files and exit 1; write nothing")
    args = ap.parse_args(argv)
    if args.check:
        bad = stale()
        for p in bad:
            print(f"STALE: {os.path.relpath(p, ROOT)} -- run: python tools/gen_settings.py")
        print("generated settings files are up to date" if not bad else f"{len(bad)} stale file(s)")
        return 1 if bad else 0
    for path, text in outputs().items():
        with open(path, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        print(f"wrote {os.path.relpath(path, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
